# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismuhammad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='publish_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='reference',
            field=models.TextField(blank=True),
        ),
    ]
